config/routes.rb
Gitty::Application.routes.draw do

  scope '_' do
    authpwn_session
    config_vars

    resources :ssh_keys

    # Users.
    get '/users' => 'users#index', as: :users
    post '/users' => 'users#create'
    get '/users/register' => 'users#new', as: :new_user
    get '/user/:user_param(.:format)' => 'users#show', as: :user,
        constraints: { user_param: /[^\/]+/ }
    get '/user/:user_param/edit(.:format)' => 'users#edit', as: :edit_user,
        constraints: { user_param: /[^\/]+/ }
    patch '/user/:user_param(.:format)' => 'users#update',
        constraints: { user_param: /[^\/]+/ }
    delete '/user/:user_param(.:format)' => 'users#destroy',
           constraints: { user_param: /[^\/]+/ }
  end

  scope '_' do
    get 'check_access.:format' => 'repositories#check_access',
        as: :repository_check_access
    post 'change_notice.:format' => 'repositories#change_notice',
         as: :repository_change_notice
  end

  # Profiles.
  get '/:profile_name(.:format)' => 'profiles#show', as: :profile,
      constraints: { profile_name: /[^_][^\/]+/ }
  patch '/:profile_name(.:format)' => 'profiles#update',
      constraints: { profile_name: /[^_][^\/]+/ }
  delete '/:profile_name(.:format)' => 'profiles#destroy',
         constraints: { profile_name: /[^_][^\/]+/ }
  scope '_' do
    resources :profiles, only: [:index, :new, :create]
    scope 'profiles' do
      get ':profile_name(.:format)' => 'profiles#show'
      get ':profile_name/edit(.:format)' => 'profiles#edit', as: :edit_profile
      patch ':profile_name(.:format)' => 'profiles#update'
      delete ':profile_name(.:format)' => 'profiles#destroy'
    end
  end

  scope ':profile_name', constraints: { profile_name: /[^_][^\/]+/ } do
    # Mis-used git-over http repository link.
    get ':repo_name.git' => 'smart_http#index',
        constraints: { repo_name: /[^\/]+/ }, format: false, as: :git_over_http

    # Repositories.
    get ':repo_name(.:format)' => 'repositories#show',
        constraints: { repo_name: /[^\/]+/ }, as: :profile_repository
    patch ':repo_name(.:format)' => 'repositories#update',
        constraints: { repo_name: /[^\/]+/ }
    delete ':repo_name(.:format)' => 'repositories#destroy',
           constraints: { repo_name: /[^\/]+/ }
    get ':repo_name/edit(.:format)' => 'repositories#edit',
        :constraints => { :repo_name => /[^\/]+/ },
        :as => :edit_profile_repository
  end
  scope '_' do
    resources :repositories, only: [:index, :new, :create]
    scope 'repositories/:profile_name' do
      get ':repo_name(.:format)' => 'repositories#show'
      get ':repo_name/edit(.:format)' => 'repositories#edit'
      patch ':repo_name(.:format)' => 'repositories#update'
      delete ':repo_name(.:format)' => 'repositories#destroy'
    end
  end

  # HTTP fetch and push.
  scope ':profile_name/:repo_name.git', constraints: {
      profile_name: /[^_\/]+/, repo_name: /[^\/]+/ } do
    post 'git-upload-pack' => 'smart_http#upload_pack'
    post 'git-receive-pack' => 'smart_http#receive_pack'
    get 'info/refs' => 'smart_http#info_refs'
    get '*path' => 'smart_http#git_file', format: false
  end

  scope ':profile_name/:repo_name',
      constraints: { profile_name: /[^_\/]+/, repo_name: /[^\/]+/ } do
    # Feed.
    get 'subscribers(.:format)' => 'feed_subscriptions#index',
        as: :subscribers_profile_repository
    post 'subscribers(.:format)' => 'feed_subscriptions#create'
    delete 'subscribers(.:format)' => 'feed_subscriptions#destroy'
    get 'feed(.:format)' => 'repositories#feed', as: :feed_profile_repository

    # Commits.
    get 'commits(/:ref_name)' => 'commits#index',
        as: :profile_repository_commits, constraints: {ref_name: /[^\/]+/ }
    get 'commit/:commit_gid(.:format)' => 'commits#show',
        as: :profile_repository_commit

    # Branches.
    get 'branches' => 'branches#index', as: :profile_repository_branches
    get 'branch/:branch_name(.:format)' => 'branches#show',
        as: :profile_repository_branch

    # Tags.
    get 'tags' => 'tags#index', as: :profile_repository_tags
    get 'tag/:tag_name' => 'tags#show', as: :profile_repository_tag,
        constraints: {tag_name: /[^\/]+/}

    # Trees.
    scope 'tree/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'trees#show', as: :profile_repository_tree
      get '/' => 'trees#show', as: :profile_repository_commit_tree
    end

    # Blobs.
    scope 'blob/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'blobs#show', as: :profile_repository_blob, format: false
    end
    scope 'raw/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'blobs#raw', as: :raw_profile_repository_blob,
                                  format: false
    end

    # Issues
    resources :issues, only: [:create]
    get 'issues' => 'issues#index', as: :profile_repository_issues
    get 'issues/new' => 'issues#new', as: :new_profile_repository_issue
    get 'issues/:issue_number' => 'issues#show', as: :profile_repository_issue
    get 'issues/:issue_number/edit(.:format)' => 'issues#edit',
        as: :edit_profile_repository_issue
    patch 'issues/:issue_number' => 'issues#update'
    delete 'issues/:issue_number' => 'issues#destroy'

    # ACLs.
    get 'acl_entries' => 'acl_entries#index', as: :profile_repository_acl_entries
    post 'acl_entries' => 'acl_entries#create'
    patch 'acl_entries/:principal_name' => 'acl_entries#update',
        as: :profile_repository_acl_entry,
        constraints: { principal_name: /[^_][^\/]+/ }
    delete 'acl_entries/:principal_name' => 'acl_entries#destroy',
        constraints: { principal_name: /[^_][^\/]+/ }
  end

  # Profile sub-resources. (must follow repository sub-resources)
  scope '_' do
    scope 'profiles/:profile_name',
          constraints: { profile_name: /[^_][^\/]+/ } do
      # ACLs.
      get 'acl_entries' => 'acl_entries#index', as: :profile_acl_entries
      post 'acl_entries' => 'acl_entries#create'
      patch 'acl_entries/:principal_name' => 'acl_entries#update',
          as: :profile_acl_entry, constraints: { principal_name: /[^_][^\/]+/ }
      delete 'acl_entries/:principal_name' => 'acl_entries#destroy',
          constraints: { principal_name: /[^_][^\/]+/ }

      # Feed.
      get 'subscribers(.:format)' => 'feed_subscriptions#index',
          as: :subscribers_profile
      post 'subscribers(.:format)' => 'feed_subscriptions#create'
      delete 'subscribers(.:format)' => 'feed_subscriptions#destroy'
    end
  end

  root to: 'session#show'
end

app/models/session.rb
# Virtual model for the information collected when a user signs in.
class Session
  include Authpwn::SessionModel

  # Add your extensions to the Session class here.
end

app/controllers/session_controller.rb
# Manages logging in and out of the application.
class SessionController < ApplicationController
  include Authpwn::SessionController

  # Sets up the 'session/welcome' view. No user is logged in.
  def welcome
    @stats = {
      users: User.count,
      repositories: Repository.count,
      commits: Commit.count,
      files: Blob.count
    }
  end
  private :welcome

  # Sets up the 'session/home' view. A user is logged in.
  def home
    # Pull information about the current user.
    @profile = current_user.profile
    unless @profile
      redirect_to new_profile_url
      return
    end
  end
  private :home

  # The notification text displayed when a session authentication fails.
  def bounce_notice_text(reason)
    case reason
    when :invalid
      'Invalid e-mail or password'
    when :expired
      'Password expired. Please click "Forget password"'
    when :blocked
      'Account blocked. Please verify your e-mail address'
    end
  end

  # A user is logged in, based on a token.
  def home_with_token(token)
    respond_to do |format|
      format.html do
        case token
        when Tokens::EmailVerification
          redirect_to session_url, notice: 'E-mail address confirmed'
        when Tokens::PasswordReset
          redirect_to change_password_session_url
        # Handle other token types here.
        end
      end
      format.json do
        # Rely on default behavior.
      end
    end
  end
  private :home_with_token

  # If true, every successful login results in a SQL query that removes expired
  # session tokens from the database, to keep its size down.
  #
  # For better performance, set this to false and periodically call
  # Tokens::SessionUid.remove_expired in background thread.
  self.auto_purge_sessions = true

  # You shouldn't extend the session controller, so you can benefit from future
  # features. But, if you must, you can do it here.
end

app/views/session/forbidden.html.erb
<h2>Access Denied</h2>

<% if current_user %>
<p>
  You don't have access to the page that you tried to see. Perhaps you need to
  sign in as a different user?
</p>
<% else %>
<p>
  Please try <%= link_to 'Signing in', new_session_path %> to see the page.
</p>
<script type="text/javascript">
window.location = "<%= new_session_path %>";
</script>
<% end %>

app/views/session/home.html.erb
<div class="home_panel feed">
  <h2>News Feed</h2>
  <%= render 'feed_items/list',
             :feed_items => @profile.recent_subscribed_feed_items %>
</div>

<div class="home_panel repositories">
  <h2>Repositories</h2>
  <p class="actions">
    <%= link_to 'New Repository', new_repository_path, :class => 'button' %>
  </p>
  <%= render 'repositories/list', :repositories => @profile.repositories %>

  <h2>Team Repositories</h2>
  <%= render 'repositories/list', :repositories => @profile.user.team_repositories %>
</div>

<div class="home_panel keys">
  <h2>SSH Keys</h2>
  <p class="actions">
    <%= link_to 'New Key', new_ssh_key_path, :class => 'button' %>
  </p>
  <% if @profile.user.ssh_keys.empty? %>
  <p>You have no SSH keys!</p>
  <p>
    <%= link_to 'Add a key', new_ssh_key_path %> to access your repositories
    via git.
  </p>
  <% else %>
  <%= render 'ssh_keys/list', :ssh_keys => @profile.user.ssh_keys %>
  <% end %>
</div>

<div class="home_panel teams">
  <h2>Teams</h2>
  <p class="actions">
    <%= link_to 'New Team', new_profile_path, :class => 'button' %>
  </p>
  <%= render 'profiles/list', :profiles => @profile.user.team_profiles %>
</div>

app/views/session/new.html.erb
<% if @redirect_url %>
<p data-alert class="alert-box">
  We need you to log in before we can show you the page that you are trying to
  view.
  <a href="#" title="Close" class="close">&times;</a>
</p>
<% end %>

<h2>Log in</h2>
<%= form_for @session, url: session_path,
             builder: FoundationFormBuilder::Icons do |f| %>

  <%= f.email_field :email, autofocus: true, required: true,
          placeholder: 'your@email.com',
          label: { icon: fa_icon('envelope'), text: 'Email Address' }  %>

  <%= f.password_field :password, required: true, placeholder: 'your password',
          label: { icon: fa_icon('key'), text: 'Password' }  %>

  <div class="row">
    <div class="small-5 small-offset-1 columns">
      <%= button_tag name: 'login', value: 'requested', type: 'submit',
                     class: 'large success button expand' do %>
        <%= fa_icon 'sign-in' %> Sign in
      <% end %>
    </div>
    <div class="small-5 columns">
      <%= button_tag name: 'reset_password', value: 'requested',
                     type: 'submit', formaction: reset_password_session_path,
                     class: 'large button expand' do %>
        <%= fa_icon '' %> Reset password
      <% end %>
    </div>
  </div>

  <% if @redirect_url %>
  <%= hidden_field_tag :redirect_url, @redirect_url %>
  <% end %>
<% end %>

app/views/session/password_change.html.erb
<h2>Password Change</h2>

<% if @credential.updated_at %>
<p class="password_age_notice">
  Your have been using the same password for
  <span class="password_age">
    <%= time_ago_in_words @credential.updated_at, include_seconds: true %>.
  </span>
</p>
<% end %>

<%= form_for @credential, url: change_password_session_path, as: :credential,
        method: :post, builder: FoundationFormBuilder do |f| %>

  <% unless @credential.new_record? %>
  <%= f.password_field :old_password, required: true,
          placeholder: 'your password', label: 'Current Password' %>
  <% end %>

  <%= f.password_field :password, required: true,
          placeholder: 'a clever new password', label: 'New Password' %>

  <%= f.password_field :password_confirmation, required: true,
          placeholder: 'same clever new password', label: 'Confirm Password' %>

  <div class="row">
    <div class="small-11 small-offset-1 columns">
      <%= f.button name: 'login', value: 'requested',
                   class: 'large success button expand' do %>
        <%= fa_icon 'check' %> Change Password
      <% end %>
    </div>
  </div>
<% end %>

app/views/session/welcome.html.erb
<div class="welcome">
  <div class="statistics">
    <p>This gitty server has</p>
    <ul>
      <li><%= pluralize @stats[:users], 'user' %></li>
      <li><%= pluralize @stats[:repositories], 'repository' %></li>
      <li><%= pluralize @stats[:commits], 'commit' %></li>
      <li><%= pluralize @stats[:files], 'file' %></li>
    </ul>
  </div>

  <p>
    Gitty is a free, open-source Web application for managing Git repositories.
  </p>

  <p>
    <%= link_to 'Sign up', new_user_path %> to collaborate with the other users!
    A gitty account lets you push and pull from Git repositories, send and receive
    comments on Git commits, and create your own repositories.
  </p>

  <p>
    If you already have an account, you should
    <%= link_to 'Sign in', new_session_path %>.
  </p>
</div>